### PR TITLE
feat: i18n support

### LINKED ISSUE #13: Localization support ?
I couldn't find an option to set the UI language in Gath.io. Is it possible ? I'd like to know how to contribute to localize it in 2 other languages if/when possible.

### PR DESCRIPTION
**Pull request by MomentQYC**
resolve #13 
Initial implementation of i18n, the future will add the part of the user's independent choice of language.
I'm relatively new to js, so please point out any errors, thanks!

### CODE REVIEW

**Comment by lowercasename** [comment]
This is a superb feat, thank you so much so far! I'm hoping to have time to review this early this month.

**Comment by MomentQYC** [comment]
When I create a new event, there is an error: 
Database error, please try again :( - ValidationError: start: Cast to date failed for value "Moment" (type Moment) at path "start", end: Cast to date failed for value "Moment" (type Moment) at path "end"
I don't know if this is related to the code I changed (after all, I know very little about js).

**Comment by lowercasename** [comment]
There's currently an issue with this implementation where nested Handlebars expressions don't get rendered, so this i18n string:

```
"hostedBy": "Hosted by {{eventData.hostName}}",
```

Comes out as:

> Hosted by

I think the easiest way to get around this is to separate the internal Handlebars expressions from the translation strings, since it seems quite complex to render nested Handlebars expressions.

**Comment by lowercasename** [comment]
> When I create a new event, there is an error: Database error, please try again :( - ValidationError: start: Cast to date failed for value "Moment" (type Moment) at path "start", end: Cast to date failed for value "Moment" (type Moment) at path "end" I don't know if this is related to the code I changed (after all, I know very little about js).

The issue here is that the event creation code expects the start and end date to be supplied in a very specific format, and that format only sends across when the datepicker is set to the `en` locale.

**Pull request closed without merging**
